import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '#app/app/globals.css'
import { Header } from '#app/components/header'
import { getOptionalUser } from '#app/lib/auth.server'
import { UserProvider } from '#app/lib/contexts/user-context'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const user = await getOptionalUser()

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<UserProvider user={user}>
					<Header />
					{children}
				</UserProvider>
			</body>
		</html>
	)
}
